from wtgseal import maker


def test_setup_header():
    expected = [
        (0, '# locust file generated by wtg-seal (release unknown)'),
        (0, '# See https://github.com/mchoji/wtg-seal for more information'), ]
    assert maker.setup_header() == expected


def test_setup_import():
    expected = [(0, 'from locust import Locust, TaskSet, task')]
    assert maker.setup_import() == expected


def test_setup_task():
    expected = [
        (1, '@task(1)'),
        (1, 'def obj0(self):'),
        (2, 'self.client.get("/1.txt")'),
        (2, 'self.client.get("/2.txt")'), ]

    assert maker.setup_task('obj', 0, 1, ['/1.txt', '/2.txt'], 1) == expected
