import pytest

from wtgseal import __version__ as dist_version
from wtgseal import maker


def test_setup_header():
    expected = [
        (0, ' '.join(['# locust file generated by wtg-seal',
                     f'(release {dist_version})'])),
        (0, '# See https://github.com/mchoji/wtg-seal for more information'), ]
    assert maker.setup_header() == expected


def test_setup_import():
    expected = [(0, 'from locust import Locust, TaskSet, task')]
    assert maker.setup_import() == expected


def test_setup_task():
    expected = [
        (1, '@task(1)'),
        (1, 'def obj0(self):'),
        (2, 'self.client.get("/1.txt")'),
        (2, 'self.client.get("/2.txt")'), ]

    assert maker.setup_task('obj0', 1, ['/1.txt', '/2.txt'], 1) == expected


def test_setup_task_wrong_uri():
    with pytest.raises(TypeError, match=r'.+should be a list'):
        maker.setup_task('obj0', 1, 2, 1)
